//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatWCF
{
    using System;
    using System.Collections.Generic;

    public partial class Cat
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Gender { get; set; }
        public int FurType { get; set; }
        public string Breed { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual FurType FurType1 { get; set; }
        public virtual Gender Gender1 { get; set; }
    }
}
